#!/bin/bash

# Vérifie si la variable d'environnement $PYFILE est définie
if [ -z "$PYFILE" ]; then
    echo "La variable d'environnement PYFILE n'est pas définie."
    exit 1
fi

# Exécute le script Python correspondant
python3 "$PYFILE"


